-- DDL para producción (TypeORM corre con `synchronize: false` cuando NODE_ENV=production).
-- En dev/e2e la tabla la crea `synchronize` a partir de `CarteraEstadisticasSnapshot`.
-- Snapshot diario de estadísticas operativas por cartera (comparación día vs día).
CREATE TABLE IF NOT EXISTS cartera_estadisticas_snapshot (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cartera_id integer NOT NULL REFERENCES carteras(id) ON DELETE CASCADE,
  fecha date NOT NULL,
  total_clientes integer NOT NULL DEFAULT 0,
  clientes_atrasados integer NOT NULL DEFAULT 0,
  clientes_vencidos integer NOT NULL DEFAULT 0,
  sin_visita_hoy integer NOT NULL DEFAULT 0,
  sin_visita_desde_ultima_liquidada integer NOT NULL DEFAULT 0,
  con_prestamos_nuevos integer NOT NULL DEFAULT 0,
  con_mas_de_un_prestamo integer NOT NULL DEFAULT 0,
  clientes_nuevos integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_cartera_estadisticas_snapshot_cartera_fecha UNIQUE (cartera_id, fecha)
);
