-- DDL para producción (TypeORM corre con `synchronize: false` cuando NODE_ENV=production).
-- En dev/e2e la tabla la crea `synchronize` a partir de `RutaEstadisticasSnapshot`.
-- Snapshot diario de estadísticas operativas por ruta (comparación día vs día).
CREATE TABLE IF NOT EXISTS ruta_estadisticas_snapshot (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ruta_id integer NOT NULL REFERENCES rutas(id) ON DELETE CASCADE,
  fecha date NOT NULL,
  total_clientes integer NOT NULL DEFAULT 0,
  clientes_atrasados integer NOT NULL DEFAULT 0,
  clientes_vencidos integer NOT NULL DEFAULT 0,
  sin_visita_hoy integer NOT NULL DEFAULT 0,
  sin_visita_desde_ultima_liquidada integer NOT NULL DEFAULT 0,
  con_prestamos_nuevos integer NOT NULL DEFAULT 0,
  con_mas_de_un_prestamo integer NOT NULL DEFAULT 0,
  clientes_nuevos integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_ruta_estadisticas_snapshot_ruta_fecha UNIQUE (ruta_id, fecha)
);
